mode: predict
debug: False
load_ckpt: experiments/vm_v2/checkpoint_best.pkl

components:
  data: predict
  transform: vm
  system: vm_v2
  model: vm_v2

writer:
  __target__: vm
  save_dir: results/dataset_test_noisy
  save_name: denoised
